# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering', models.IntegerField()),
                ('published_date', models.DateField()),
                ('type', models.CharField(max_length=32)),
                ('cd_title', models.CharField(max_length=200)),
                ('disk', models.IntegerField()),
                ('track', models.IntegerField()),
                ('music_title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('arranger', models.CharField(max_length=100)),
            ],
        ),
    ]
